build:
	GOOS=linux GOARCH=amd64 go build -o bin/blog-md-linux-amd64 .
	GOOS=darwin GOARCH=amd64 go build -o bin/blog-md-darwin-amd64 .
	GOOS=darwin GOARCH=arm64 go build -o bin/blog-md-darwin-arm64 .
